# Generated by Django 5.0.3 on 2024-04-27 18:44

import App_Register.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', App_Register.models.LowercaseEmailField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('gender', models.BooleanField(default=False)),
                ('technical_skill', models.BooleanField(default=False)),
                ('heard_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
