# Generated by Django 5.0.3 on 2024-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='heard_by',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Friend', 'Friend'), ('Others', 'Others')], default='', max_length=100, null=True),
        ),
    ]
