# Generated by Django 5.0.3 on 2024-12-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Register', '0002_alter_register_heard_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='date_reg',
            new_name='date',
        ),
    ]
